stages:
  - build
  - release

variables:
  SCHEMA_REGISTRY_VERSION: '3.0.1'
  SCHEMA_REGISTRY_VERSION_MAJOR: '3'
  SCHEMA_REGISTRY_VERSION_MINOR: '0'
  SCHEMA_REGISTRY_VERSION_PATCH: '1'

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.ucalgary.ca

build:
  stage: build
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $SCHEMA_REGISTRY_VERSION_MAJOR.$SCHEMA_REGISTRY_VERSION_MINOR
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

release:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:$SCHEMA_REGISTRY_VERSION_MAJOR.$SCHEMA_REGISTRY_VERSION_MINOR.$SCHEMA_REGISTRY_VERSION_PATCH
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:$SCHEMA_REGISTRY_VERSION_MAJOR.$SCHEMA_REGISTRY_VERSION_MINOR
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:$SCHEMA_REGISTRY_VERSION_MAJOR
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$SCHEMA_REGISTRY_VERSION_MAJOR.$SCHEMA_REGISTRY_VERSION_MINOR.$SCHEMA_REGISTRY_VERSION_PATCH
    - docker push $CI_REGISTRY_IMAGE:$SCHEMA_REGISTRY_VERSION_MAJOR.$SCHEMA_REGISTRY_VERSION_MINOR
    - docker push $CI_REGISTRY_IMAGE:$SCHEMA_REGISTRY_VERSION_MAJOR
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
