image: docker.ucalgary.ca/rms-utils/rms-ci:latest

stages:
  - build

variables:
  BUILD_CONTEXT_PATH: '3'
  IMAGE_TAG: $CI_BUILD_REF_NAME

before_script:
  - &ci_registry_image_default
    if [ -z ${CI_REGISTRY_IMAGE+x} ]; then
      export CI_REGISTRY_IMAGE=`basename $CI_BUILD_REPO`; fi

Build Image: &build_image
  stage: build
  before_script:
    - *ci_registry_image_default
    - if [ -n "${CI_BUILD_TOKEN}" ]; then 
        docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY; fi
  script:
    - docker build
        --pull
        --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG
        $BUILD_CONTEXT_PATH
  after_script:
    - if [ -n "${CI_BUILD_TOKEN}" ]; then
        docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG; fi
